config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'application#index'

  resources :transactions,          only: [:show, :index]
  resources :users,                 only: :index
  resources :payments,              only: [:new, :create, :index, :show]
  resources :withdrawals,           only: [:new, :create, :index, :show]
  resources :payment_gateways,      only: :create
  resources :withdrawal_gateways,   only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/accountable.rb
module Accountable
  extend ActiveSupport::Concern

  included do
    has_many :debit_transactions,  class_name: 'Transaction', as: :debit
    has_many :credit_transactions, class_name: 'Transaction', as: :credit
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  include Accountable
  include AASM

  belongs_to :user

  aasm column: :state do
    state :new, initial: true
    state :executed
    state :rejected

    event :reject do
      transitions from: :new, to: :rejected
    end

    event :execute do
      before do
        transaction = Transaction.create debit: self, credit: user, subject: self, sum: self.sum
        transaction.execute
      end

      transitions from: :new, to: :executed
    end
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  include AASM

  belongs_to :credit,  polymorphic: true
  belongs_to :debit,   polymorphic: true
  belongs_to :subject, polymorphic: true

  validates_presence_of :credit, :debit

  aasm column: :state do
    state :new, initial: true
    state :executed
    state :rejected

    event :reject do
      transitions from: :new, to: :rejected
    end

    event :execute do
      before do
        debit.increment(:balance, - sum)
        debit.save
        update(debit_balance: debit.balance)
      end

      transitions from: :new, to: :executed

      after do
        credit.increment(:balance, sum)
        credit.save
        update(credit_balance: credit.balance)
      end
    end
  end

  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  include Accountable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :payments
  has_many :withdrawals

  validates :email, uniqueness: true
  validates :phone, uniqueness: true

  validates_presence_of :email, :phone, :name, :surname, :patronymic
  validates :balance, numericality: { greater_than_or_equal_to: 0 }
end

app/models/withdrawal.rb
class Withdrawal < ApplicationRecord
  include Accountable
  include AASM

  belongs_to :user

  aasm column: :state do
    state :new, initial: true
    state :executed
    state :rejected

    event :reject do
      transitions from: :new, to: :rejected
    end

    event :execute do
      after do
        transaction = Transaction.create debit: user, credit: self, subject: self, sum: sum
        transaction.execute
      end

      transitions from: :new, to: :executed, if: :can_withdrawal?
    end
  end

  def can_withdrawal?
    user.balance >= sum
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def index

  end
end

app/controllers/payment_gateways_controller.rb
class PaymentGatewaysController < ApplicationController

  def create
    @payment = Payment.where(id: params[:payment_id]).any? ? Payment.where(id: params[:payment_id]).first : nil
    if @payment && @payment.sum == params[:sum].to_i
      @payment.execute
      @payment.save
    end
    redirect_to @payment
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def index
    @payments = current_user.payments
  end

  def show
    @payment = Payment.where(id: params[:id]).first
  end


  def new
    @payment = Payment.new user_id: params[:user_id] || current_user.to_param
  end

  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: "Платеж на сумму #{@payment.sum} успешно создан" }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def payment_params
    params.require(:payment).permit :sum, :user_id
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = current_user.debit_transactions + current_user.credit_transactions
  end

  def show
    @transaction = Transaction.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :surname, :patronymic, :phone)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
  end
end

app/controllers/withdrawal_gateways_controller.rb
class WithdrawalGatewaysController < ApplicationController

  add_flash_types :balance_error

  def create
    @withdrawal = Withdrawal.where(id: params[:withdrawal_id]).any? ? Withdrawal.where(id: params[:withdrawal_id]).first : nil
    if @withdrawal && @withdrawal.sum == params[:sum].to_i
      if @withdrawal.may_execute?
        @withdrawal.execute
        @withdrawal.save
        redirect_to @withdrawal
      else
        redirect_to withdrawals_path, balance_error: "На счету недостаточно средств!"
      end
    end
  end
end

app/controllers/withdrawals_controller.rb
class WithdrawalsController < ApplicationController

  add_flash_types :balance_error

  def index
    @withdrawals = current_user.withdrawals
  end

  def show
    @withdrawal = Withdrawal.where(id: params[:id]).first
  end


  def new
    @withdrawal = Withdrawal.new user_id: params[:user_id] || current_user.to_param
  end

  def create
    @withdrawal = Withdrawal.new(withdrawal_params)

    respond_to do |format|
      if @withdrawal.sum <= @withdrawal.user.balance
        if @withdrawal.save
          format.html { redirect_to @withdrawal, notice: "Вывод средств на сумму #{@withdrawal.sum} успешно создан" }
          format.json { render :show, status: :created, location: @withdrawal }
        else
          format.html { render :new }
          format.json { render json: @withdrawal.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to new_withdrawal_path, balance_error: "На счету недостаточно средств!"}
      end
    end
  end

  private

  def withdrawal_params
    params.require(:withdrawal).permit :sum, :user_id, :reason
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/application/index.slim
- if current_user
  h2.text-center Добро пожаловать в панель управления
  h3.text-center  Выберите нужный пункт в меню
- else
  .form-signin
    = link_to new_session_path('user')
      .btn.btn-lg.btn-primary.btn-block Войти в систему

app/views/layouts/application.html.slim
doctype html
html
  head
    title Sirena Test Work
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag "application", 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags

  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Test work", root_path, class: 'navbar-brand'
        #navbar.navbar-collapse.collapse
          ul.nav.navbar-nav.navbar-right
            li class='#{'active' if current_page? new_session_path('user')}'
              - if current_user
                = link_to "Выход", destroy_user_session_path, :method => 'delete'
              - else
                = link_to "Вход", new_session_path('user')
          form.navbar-form.navbar-right
            - if current_user
              h5.text-primary = "#{current_user.email} Баланс: #{current_user.balance}"
    .container-fluid
      .row
        .col-sm-3.col-md-2.sidebar
          .row
            - if current_user
              ul.nav.nav-sidebar
                li class='#{'active' if current_page? users_path}'
                  - if current_user.has_access_to_crm
                    = link_to "Список всех пользователей", users_path
                li class='#{'active' if current_page? transactions_path}'
                  = link_to "Список транзакций", transactions_path
                li class='#{'active' if current_page? payments_path}'
                  = link_to "Список пополнений", payments_path
                li class='#{'active' if current_page? withdrawals_path}'
                  = link_to "Список выводов", withdrawals_path
                li class='#{'active' if current_page? new_payment_path}'
                  = link_to "Пополнить баланс", new_payment_path
                li class='#{'active' if current_page? new_withdrawal_path}'
                  = link_to "Вывести деньги", new_withdrawal_path
            - else
              p Доступ закрыт. Необходимо войти в систему
        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
          = yield

app/views/payments/index.html.slim
h1.page-header Панель управления

h2.sub-header Список пополнений
.table-responsive
  table.table.table-striped
    thead
      tr
        th #
        th Сумма
        th Платежный шлюз
        th Состояние
        th Причина
        th Действия
    tbody
      - @payments.each do |payment|
        tr
          td = payment.id
          td = payment.sum
          td = payment.gateway
          td = payment.state
          td = payment.reason
          td
            - if payment.new?
              = link_to payment_gateways_path(sum: payment.sum, payment_id: payment.to_param), method: :post
                .btn.btn-success Произвести оплату
            - else
              | Нет доступных действий

app/views/payments/new.html.slim
.form-signin
  = form_for(@payment) do |f|
    h2.form-signin-heading Новый платеж

    = f.label :sum, class: 'sr-only'
      | Сумма
    = f.number_field :sum, min: 1, autofocus: true, class: 'form-control', placeholder: 'Сумма'

    = f.label :reason, class: 'sr-only'
      | Пояснение
    = f.text_field :reason, min: 1, autofocus: true, class: 'form-control', placeholder: 'Пояснение'

    = f.hidden_field :user_id, value: @payment.user_id


    br
    = f.submit 'Создать', class: 'btn btn-lg btn-primary btn-block'

app/views/payments/show.html.slim
p#notice = notice

h2.sub-header Детали платежа
.table-responsive
  table.table.table-striped
    thead
      tr
        th #
        th Платежный шлюз
        th Сумма
        th Состояние
    tbody
      tr
        td = @payment.id
        td = @payment.gateway
        td = @payment.sum
        td = @payment.state

- if @payment.new?
  h3 = "Чтобы имитировать ответ от сервера платежного шлюза нажмите кнопку"

  .form-signin
    = link_to payment_gateways_path(sum: @payment.sum, payment_id: @payment.to_param), method: :post
      .btn.btn-lg.btn-primary.btn-block Произвести оплату

app/views/transactions/index.html.slim
h1.page-header Панель управления

h2.sub-header Список транзакций
.table-responsive
  table.table.table-striped
    thead
      tr
        th #
        th Дебет
        th Кредит
        th Тема
        th Сумма
        th Состояние
    tbody
      - @transactions.each do |transaction|
        tr
          td = transaction.id
          td = transaction.debit.class
          td = transaction.credit.class
          td = transaction.subject.class
          td = transaction.sum
          td = transaction.state

app/views/transactions/show.html.slim
h2.sub-header Детали транзакции
.table-responsive
  table.table.table-striped
    thead
      tr
        th #
        th Дебет
        th Кредит
        th Тема
        th Сумма
        th Состояние
    tbody
      tr
        td = @transaction.id
        td = @transaction.debit.class
        td = @transaction.credit.class
        td = @transaction.subject.class
        td = @transaction.sum
        td = @transaction.state

app/views/users/index.html.slim
h1.page-header Панель управления

- if current_user.has_access_to_crm
  h2.sub-header Список пользователей
  .table-responsive
    table.table.table-striped
      thead
        tr
          th #
          th Фамилия
          th Имя
          th Отчество
          th E-mail
          th Телефон
          th Баланс
          th Действия
      tbody
        - @users.each do |user|
          tr
            td = user.id
            td = user.surname
            td = user.name
            td = user.patronymic
            td = user.email
            td = user.phone
            td = user.balance
            td
              = link_to 'Пополнить баланс', new_payment_path({user_id: user.id})
              br
              = link_to 'Вывести деньги', new_withdrawal_path({user_id: user.id})
- else
  h3.text-center.alert-warning У вас нет доступа в данный раздел.

app/views/withdrawals/index.html.slim
h1.page-header Панель управления

h2.sub-header Список выводов
.table-responsive
  .alert-warning = balance_error
  table.table.table-striped
    thead
      tr
        th #
        th Сумма
        th Состояние
        th Причина
        th Действия
    tbody
      - @withdrawals.each do |withdrawal|
        tr
          td = withdrawal.id
          td = withdrawal.sum
          td = withdrawal.state
          td = withdrawal.reason
          td
            - if withdrawal.new?
              = link_to withdrawal_gateways_path(sum: withdrawal.sum, withdrawal_id: withdrawal.to_param), method: :post
                .btn.btn-success Вывести деньги
            - else
              | Нет доступных действий

app/views/withdrawals/new.html.slim
.form-signin
  .alert-warning = balance_error
  = form_for(@withdrawal) do |f|
    h2.form-signin-heading Вывод денег

    = f.label :sum, class: 'sr-only'
      | Сумма
    = f.number_field :sum, min: 1, autofocus: true, class: 'form-control', placeholder: 'Сумма'

    = f.label :reason, class: 'sr-only'
      | Пояснение
    = f.text_field :reason, min: 1, autofocus: true, class: 'form-control', placeholder: 'Пояснение'

    = f.hidden_field :user_id, value: @withdrawal.user_id


    br
    = f.submit 'Вывести', class: 'btn btn-lg btn-primary btn-block'

app/views/withdrawals/show.html.slim
p#notice = notice

h2.sub-header Детали вывода средств
.table-responsive
  table.table.table-striped
    thead
      tr
        th #
        th Причина
        th Сумма
        th Состояние
    tbody
      tr
        td = @withdrawal.id
        td = @withdrawal.reason
        td = @withdrawal.sum
        td = @withdrawal.state

- if @withdrawal.new?
  h3 = "Чтобы имитировать ответ от сервера платежного шлюза нажмите кнопку"

  .form-signin
    = link_to withdrawal_gateways_path(sum: @withdrawal.sum, withdrawal_id: @withdrawal.to_param), method: :post
      .btn.btn-lg.btn-primary.btn-block Вывести деньги